package project;

import java.awt.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

public class frm_Faculty extends javax.swing.JFrame
{
    //Object of class
    frm_Welcome obj_frm_Welcome;
    Faculty obj_Faculty;
    Event obj_Event;
    frm_Proposals obj_frm_Proposals;
    frm_Update_Event obj_frm_Update_Event;

    //The passed object from frm_login is checked here and then casted in to Faculty object
    public frm_Faculty(Object obj_Who)
    {
        try
        {
            if (obj_Who != null && obj_Who instanceof Faculty)
            {
                obj_Faculty = (Faculty) obj_Who;
                obj_Event = new Event();
                obj_Event.getData_Event();
            }

            initComponents();
            this.setTitle("Faculty Form");
            this.setSize(700, 500);
            this.scaleBckgrd();
            this.setData();
            this.setLocationRelativeTo(null);
            this.setResizable(false);
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            //sets rootPanel transparent so image can to shown and sets size of rootpanel same as JFrame
            this.rootPanel.setOpaque(false);
            this.rootPanel.setSize(this.getWidth(), this.getHeight());
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    //Method to set background image on lbl_Bckgrd
    public void scaleBckgrd()
    {
        //Scaling Image for lbl_Bckgrd (Main Background)
        lbl_Bckgrd.setSize(this.getWidth(), this.getHeight());
        ImageIcon ic_Bckgrd = new ImageIcon(getClass().getResource("/resources/bckgrd_Student.jpg"));
        Image img_Bckgrd = ic_Bckgrd.getImage();
        Image imgScaled_Bckgrd = img_Bckgrd.getScaledInstance(lbl_Bckgrd.getWidth(), lbl_Bckgrd.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaled_Bckgrd = new ImageIcon(imgScaled_Bckgrd);
        lbl_Bckgrd.setIcon(scaled_Bckgrd);
    }

    //Method to set data on text fields by fetching it from DB
    public void setData()
    {
        lbl_f_Name.setText("Name: " + obj_Faculty.getName());
        lbl_f_ID.setText("ID: " + obj_Faculty.getId());

        //CODE for fetching data from DB from tbl_Up_Events and show on table
        //Things for DB
        //Connection_to_DB it connects to Access DB
        Connect_to_DB obj_conDB = new Connect_to_DB();
        Connection obj_con = obj_conDB.make_Connection();

        //Statement is used for updating, inserting and deleting
        Statement stmt = null;
        ResultSet res = null;

        try
        {
            stmt = obj_con.createStatement();

            String str_Data = "select * from tbl_Up_Events";

            res = stmt.executeQuery(str_Data);

            while (res.next())
            {
                String Name = res.getString("evntName");
                String Day = res.getString("evntDay");
                String Date = res.getString("evntDate");
                String Venue = res.getString("evntVenue");
                String Budget = res.getString("evntBudget");
                String Descript = res.getString("evntDescript");
                String Club = res.getString("evntClub");
                String Ticket = res.getString("evntTicket");

                String table[] =
                {
                    Name, Day, Date, Venue, Budget, Descript, Club, Ticket
                };

                DefaultTableModel tblModel = (DefaultTableModel) tbl_Event.getModel();
                tblModel.addRow(table);
            }

            obj_con.close();

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        //CODE for tables ENDS
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rootPanel = new javax.swing.JPanel();
        lbl_UpEvent = new javax.swing.JLabel();
        btn_Pro_Event = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        lbl_f_Name = new javax.swing.JLabel();
        lbl_f_ID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Event = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbl_Bckgrd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        rootPanel.setForeground(new java.awt.Color(255, 255, 255));
        rootPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        lbl_UpEvent.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_UpEvent.setForeground(new java.awt.Color(255, 255, 255));
        lbl_UpEvent.setText("Upcoming Events");

        btn_Pro_Event.setText("View Proposals");
        btn_Pro_Event.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_Pro_EventMouseClicked(evt);
            }
        });

        btn_Exit.setText("Sign Out");
        btn_Exit.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_ExitMouseClicked(evt);
            }
        });

        lbl_f_Name.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbl_f_Name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_f_Name.setText("lbl_f_Name");

        lbl_f_ID.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbl_f_ID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_f_ID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_f_ID.setText("lbl_f_ID");

        tbl_Event.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Name", "Day", "Date", "Venue", "Budget", "Descript", "Club", "Ticket"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tbl_Event.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tbl_EventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Event);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Click on Event Name update");

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_UpEvent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(lbl_f_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(272, 272, 272)
                                .addComponent(lbl_f_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(btn_Pro_Event)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_f_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_f_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_UpEvent)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pro_Event, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        getContentPane().add(rootPanel);
        rootPanel.setBounds(0, 0, 700, 500);
        getContentPane().add(lbl_Bckgrd);
        lbl_Bckgrd.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method for btn_Exit (it takes back to frm_Welcome i.e Welcome Screen)
    private void btn_ExitMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_ExitMouseClicked
    {//GEN-HEADEREND:event_btn_ExitMouseClicked
        this.dispose();
        obj_frm_Welcome = new frm_Welcome();
        obj_frm_Welcome.setVisible(true);
    }//GEN-LAST:event_btn_ExitMouseClicked

    //Method for btn_Pro_Event (it takes us to frm_Proposals)
    private void btn_Pro_EventMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_Pro_EventMouseClicked
    {//GEN-HEADEREND:event_btn_Pro_EventMouseClicked
        try
        {
            this.setVisible(false);
            obj_frm_Proposals = new frm_Proposals(this);
            obj_frm_Proposals.setVisible(true);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_Pro_EventMouseClicked

    private void tbl_EventMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tbl_EventMouseClicked
    {//GEN-HEADEREND:event_tbl_EventMouseClicked
        try
        {
            int index = tbl_Event.getSelectedRow();
            TableModel Model = tbl_Event.getModel();

            String Name = Model.getValueAt(index, 0).toString();
            String Date = Model.getValueAt(index, 1).toString();
            String Day = Model.getValueAt(index, 2).toString();
            String Venue = Model.getValueAt(index, 3).toString();
            String Budget = Model.getValueAt(index, 4).toString();
            String Descript = Model.getValueAt(index, 5).toString();
            String Club = Model.getValueAt(index, 6).toString();
            String Ticket = Model.getValueAt(index, 7).toString();

            obj_frm_Update_Event = new frm_Update_Event();

            obj_frm_Update_Event.setTxt_Name(Name);
            obj_frm_Update_Event.setTxt_Date(Date);
            obj_frm_Update_Event.setTxt_Day(Day);
            obj_frm_Update_Event.setTxt_Venue(Venue);
            obj_frm_Update_Event.setTxt_Budget(Budget);
            obj_frm_Update_Event.setTxt_Descript(Descript);
            obj_frm_Update_Event.setTxt_Club(Club);
            obj_frm_Update_Event.setTxt_Ticket(Ticket);
            obj_frm_Update_Event.setVisible(true);

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_tbl_EventMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Pro_Event;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Bckgrd;
    private javax.swing.JLabel lbl_UpEvent;
    private javax.swing.JLabel lbl_f_ID;
    private javax.swing.JLabel lbl_f_Name;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JTable tbl_Event;
    // End of variables declaration//GEN-END:variables
}
