package project;

import java.awt.Image;
import javax.swing.ImageIcon;

public class frm_Welcome extends javax.swing.JFrame
{
    //Objects of Classes  
    frm_Login obj_frmLogin;
    frm_Booking obj_frm_Booking;

    public frm_Welcome()
    {
        initComponents();
        this.setTitle("Event Management System");
        this.setSize(1310, 820);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.scaleBckgrd();
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    //METHODS
    //Method to fit image to components
    private void scaleBckgrd()
    {
        //Image Scaling for Main Background
        ImageIcon ic_Bckgrd = new ImageIcon(getClass().getResource("/resources/bckgrd_Welcome.png"));
        Image img = ic_Bckgrd.getImage();
        Image imgScale = img.getScaledInstance(lbl_Bckgrd.getWidth(), lbl_Bckgrd.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaled_Bckgrd = new ImageIcon(imgScale);
        lbl_Bckgrd.setIcon(scaled_Bckgrd);

        //Button Image Scaling for Student Login
        ImageIcon ic_Std = new ImageIcon(getClass().getResource("/resources/icon_Student.png"));
        Image img_Std = ic_Std.getImage();
        Image imgScale_Std = img_Std.getScaledInstance(btn_Std_Login.getWidth(), btn_Std_Login.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaled_Std = new ImageIcon(imgScale_Std);
        btn_Std_Login.setIcon(scaled_Std);

        //Button Image Scaling for Faculty Login
        ImageIcon ic_Faculty = new ImageIcon(getClass().getResource("/resources/icon_Faculty.png"));
        Image img_Faculty = ic_Faculty.getImage();
        Image imgScale_Faculty = img_Faculty.getScaledInstance(btn_Faculty_Login.getWidth(), btn_Faculty_Login.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaled_Faculty = new ImageIcon(imgScale_Faculty);
        btn_Faculty_Login.setIcon(scaled_Faculty);

        //Button Image Scaling for Register
        ImageIcon ic_Reg = new ImageIcon(getClass().getResource("/resources/icon_Register.png"));
        Image img_Reg = ic_Reg.getImage();
        Image imgScale_Reg = img_Reg.getScaledInstance(btn_Register.getWidth(), btn_Register.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaled_Reg = new ImageIcon(imgScale_Reg);
        btn_Register.setIcon(scaled_Reg);

        //Setting Gifs Locations
        ImageIcon ic_Gif = new ImageIcon(getClass().getResource("/resources/confetti.gif"));
        lbl_gif1.setIcon(ic_Gif);
        lbl_gif2.setIcon(ic_Gif);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rootPanel = new javax.swing.JPanel();
        lbl_gif1 = new javax.swing.JLabel();
        lbl_gif2 = new javax.swing.JLabel();
        lbl_Register = new javax.swing.JLabel();
        btn_Std_Login = new javax.swing.JButton();
        lbl_Std_Login = new javax.swing.JLabel();
        btn_Faculty_Login = new javax.swing.JButton();
        lbl_Faculty_Login = new javax.swing.JLabel();
        btn_Register = new javax.swing.JButton();
        btn_Close = new javax.swing.JButton();
        lbl_Bckgrd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setLayout(null);
        rootPanel.add(lbl_gif1);
        lbl_gif1.setBounds(690, 160, 610, 490);
        rootPanel.add(lbl_gif2);
        lbl_gif2.setBounds(0, 160, 660, 490);
        rootPanel.add(lbl_Register);
        lbl_Register.setBounds(520, 340, 292, 0);

        btn_Std_Login.setToolTipText("");
        btn_Std_Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Std_Login.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_Std_LoginMouseClicked(evt);
            }
        });
        rootPanel.add(btn_Std_Login);
        btn_Std_Login.setBounds(1190, 20, 70, 70);

        lbl_Std_Login.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Std_Login.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Std_Login.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_Std_Login.setText("<html>Student Login</html>");
        lbl_Std_Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rootPanel.add(lbl_Std_Login);
        lbl_Std_Login.setBounds(1200, 80, 60, 60);

        btn_Faculty_Login.setToolTipText("");
        btn_Faculty_Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Faculty_Login.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_Faculty_LoginMouseClicked(evt);
            }
        });
        rootPanel.add(btn_Faculty_Login);
        btn_Faculty_Login.setBounds(1090, 20, 70, 70);

        lbl_Faculty_Login.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Faculty_Login.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Faculty_Login.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_Faculty_Login.setText("<html>Faculty Login</html>");
        lbl_Faculty_Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rootPanel.add(lbl_Faculty_Login);
        lbl_Faculty_Login.setBounds(1100, 80, 60, 60);

        btn_Register.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Register.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_RegisterMouseClicked(evt);
            }
        });
        rootPanel.add(btn_Register);
        btn_Register.setBounds(530, 300, 220, 130);

        btn_Close.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Close.setText("Close");
        btn_Close.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_CloseMouseClicked(evt);
            }
        });
        rootPanel.add(btn_Close);
        btn_Close.setBounds(1190, 710, 80, 30);
        rootPanel.add(lbl_Bckgrd);
        lbl_Bckgrd.setBounds(0, 0, 1300, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Button Student Login
    private void btn_Std_LoginMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_Std_LoginMouseClicked
    {//GEN-HEADEREND:event_btn_Std_LoginMouseClicked
        //Sending person_login as "std" so method in User Login Class chk_Login knows to run query on tbl_Std_Login in Access DB
        this.setVisible(false);
        obj_frmLogin = new frm_Login("std");
        obj_frmLogin.setVisible(true);
    }//GEN-LAST:event_btn_Std_LoginMouseClicked

    //Button Faculty Login
    private void btn_Faculty_LoginMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_Faculty_LoginMouseClicked
    {//GEN-HEADEREND:event_btn_Faculty_LoginMouseClicked
        //Sending person_login as "faculty" so method in User Login Class chk_Login knows to run query on tbl_Faculty_Login in Access DB
        this.setVisible(false);
        obj_frmLogin = new frm_Login("faculty");
        obj_frmLogin.setVisible(true);
    }//GEN-LAST:event_btn_Faculty_LoginMouseClicked

    //Method for btn_Register (it takes user to register for event)
    private void btn_RegisterMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_RegisterMouseClicked
    {//GEN-HEADEREND:event_btn_RegisterMouseClicked
        obj_frm_Booking = new frm_Booking();
        this.setVisible(false);
        obj_frm_Booking.setVisible(true);
    }//GEN-LAST:event_btn_RegisterMouseClicked

    //Method for btn_Close
    private void btn_CloseMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_CloseMouseClicked
    {//GEN-HEADEREND:event_btn_CloseMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btn_CloseMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Close;
    private javax.swing.JButton btn_Faculty_Login;
    private javax.swing.JButton btn_Register;
    private javax.swing.JButton btn_Std_Login;
    private javax.swing.JLabel lbl_Bckgrd;
    private javax.swing.JLabel lbl_Faculty_Login;
    private javax.swing.JLabel lbl_Register;
    private javax.swing.JLabel lbl_Std_Login;
    private javax.swing.JLabel lbl_gif1;
    private javax.swing.JLabel lbl_gif2;
    private javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables
}
