package project;

import java.awt.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class frm_Student extends javax.swing.JFrame
{
    //Object of class
    frm_Welcome obj_frm_Welcome;
    Student obj_Std;
    Event obj_Event;
    frm_Pro_Event obj_frm_Pro_Event;

    //The passed object from frm_login is checked here and then casted in to Student object
    public frm_Student(Object obj_Who)
    {
        try
        {
            if (obj_Who != null && obj_Who instanceof Student)
            {
                obj_Std = (Student) obj_Who;
                obj_Event = new Event();
                obj_Event.setClub(obj_Std.getClub());
                obj_Event.getData_Event();
            }

            initComponents();
            this.setTitle("Student Form");
            this.setSize(500, 550);
            this.scaleBckgrd();
            this.setData();
            this.setLocationRelativeTo(null);
            this.setResizable(false);
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            //sets rootPanel transparent so image can to shown and sets size of rootpanel same as JFrame
            this.rootPanel.setOpaque(false);
            this.rootPanel.setSize(this.getWidth(), this.getHeight());
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    //GETTERS
    public String getLbl_Club()
    {
        return lbl_Club.getText();
    }

    public String getLbl_StdID()
    {
        return lbl_StdID.getText();
    }

    public String getLbl_StdName()
    {
        return lbl_StdName.getText();
    }

    //Method to set background image on lbl_Bckgrd
    public void scaleBckgrd()
    {
        //Scaling Image for lbl_Bckgrd (Main Background)
        lbl_Bckgrd.setSize(this.getWidth(), this.getHeight());
        ImageIcon ic_Bckgrd = new ImageIcon(getClass().getResource("/resources/bckgrd_Student.jpg"));
        Image img_Bckgrd = ic_Bckgrd.getImage();
        Image imgScaled_Bckgrd = img_Bckgrd.getScaledInstance(lbl_Bckgrd.getWidth(), lbl_Bckgrd.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaled_Bckgrd = new ImageIcon(imgScaled_Bckgrd);
        lbl_Bckgrd.setIcon(scaled_Bckgrd);
    }

    //Method to set data on text fields by fetching it from DB
    public void setData()
    {
        lbl_Club.setText(obj_Std.getClub());
        lbl_StdName.setText("Name: " + obj_Std.getName());
        lbl_StdID.setText("ID: " + obj_Std.getId());

        //CODE for fetching data from DB tbl_Up_Event and show on table
        //Things for DB
        //Connection_to_DB it connects to Access DB
        Connect_to_DB obj_conDB = new Connect_to_DB();
        Connection obj_con = obj_conDB.make_Connection();

        //Statement is used for updating, inserting and deleting
        Statement stmt = null;
        ResultSet res = null;

        try
        {
            stmt = obj_con.createStatement();

            String str_Data = "select * from tbl_Up_Events";

            res = stmt.executeQuery(str_Data);

            while (res.next())
            {
                String Name = res.getString("evntName");
                String Day = res.getString("evntDay");
                String Date = res.getString("evntDate");
                String Venue = res.getString("evntVenue");

                String table[] =
                {
                    Name, Day, Date, Venue
                };

                DefaultTableModel tblModel = (DefaultTableModel) tbl_Event.getModel();
                tblModel.addRow(table);
            }

            obj_con.close();

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        //CODE for table END
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rootPanel = new javax.swing.JPanel();
        lbl_Club = new javax.swing.JLabel();
        lbl_UpEvent = new javax.swing.JLabel();
        btn_pro_Event = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        lbl_StdName = new javax.swing.JLabel();
        lbl_StdID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Event = new javax.swing.JTable();
        lbl_Bckgrd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        rootPanel.setForeground(new java.awt.Color(255, 255, 255));
        rootPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        lbl_Club.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_Club.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Club.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Club.setText("lbl_Club");

        lbl_UpEvent.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_UpEvent.setForeground(new java.awt.Color(255, 255, 255));
        lbl_UpEvent.setText("Upcoming Events");

        btn_pro_Event.setText("Propose Event");
        btn_pro_Event.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_pro_EventMouseClicked(evt);
            }
        });

        btn_Exit.setText("Sign Out");
        btn_Exit.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_ExitMouseClicked(evt);
            }
        });

        lbl_StdName.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbl_StdName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_StdName.setText("lbl_StdName");

        lbl_StdID.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbl_StdID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_StdID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_StdID.setText("lbl_StdID");

        tbl_Event.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Name", "Day", "Date", "Venue"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Event);

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rootPanelLayout.createSequentialGroup()
                        .addComponent(btn_pro_Event, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_UpEvent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Club, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addComponent(lbl_StdName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(lbl_StdID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_StdName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_StdID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_Club)
                .addGap(18, 18, 18)
                .addComponent(lbl_UpEvent)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_pro_Event, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(rootPanel);
        rootPanel.setBounds(0, 0, 500, 500);
        getContentPane().add(lbl_Bckgrd);
        lbl_Bckgrd.setBounds(0, 0, 800, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method for btn_Exit
    private void btn_ExitMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_ExitMouseClicked
    {//GEN-HEADEREND:event_btn_ExitMouseClicked
        this.dispose();
        obj_frm_Welcome = new frm_Welcome();
        obj_frm_Welcome.setVisible(true);
    }//GEN-LAST:event_btn_ExitMouseClicked

    //Method for btn_pro_Event (it opens new frm_Pro_Event)
    private void btn_pro_EventMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_pro_EventMouseClicked
    {//GEN-HEADEREND:event_btn_pro_EventMouseClicked
        this.setVisible(false);
        obj_frm_Pro_Event = new frm_Pro_Event(this);
        obj_frm_Pro_Event.setVisible(true);
    }//GEN-LAST:event_btn_pro_EventMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_pro_Event;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Bckgrd;
    private javax.swing.JLabel lbl_Club;
    private javax.swing.JLabel lbl_StdID;
    private javax.swing.JLabel lbl_StdName;
    private javax.swing.JLabel lbl_UpEvent;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JTable tbl_Event;
    // End of variables declaration//GEN-END:variables
}
