package project;

import java.awt.*;
import javax.swing.*;

public class frm_Des_Event extends javax.swing.JFrame
{
    //Object of classes
    Event obj_Event;
    
    public frm_Des_Event()
    {
        try
        {
            initComponents();
            this.setTitle("Pending Event");
            this.setSize(700, 680);
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.scaleBckgrd();
            this.setResizable(false);
            this.setLocationRelativeTo(null);
            
            obj_Event = new Event();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    //Method to set background image on lbl_Bckgrd
    public void scaleBckgrd()
    {
        //Scaling Image for lbl_Bckgrd (Main Background)
        lbl_Bckgrd.setSize(this.getWidth(), this.getHeight());
        ImageIcon ic_Bckgrd = new ImageIcon(getClass().getResource("/resources/bckgrd_Student.jpg"));
        Image img_Bckgrd = ic_Bckgrd.getImage();
        Image imgScaled_Bckgrd = img_Bckgrd.getScaledInstance(lbl_Bckgrd.getWidth(), lbl_Bckgrd.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaled_Bckgrd = new ImageIcon(imgScaled_Bckgrd);
        lbl_Bckgrd.setIcon(scaled_Bckgrd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbl_Day = new javax.swing.JLabel();
        txt_Venue = new javax.swing.JTextField();
        lbl_Name = new javax.swing.JLabel();
        lbl_Venue = new javax.swing.JLabel();
        lbl_Budget = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_Descript = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        txt_Date = new javax.swing.JTextField();
        txt_Day = new javax.swing.JTextField();
        txt_Budget = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Descript = new javax.swing.JTextArea();
        btn_Approve = new javax.swing.JButton();
        btn_Reject = new javax.swing.JButton();
        lbl_Reject_Reason = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Reject = new javax.swing.JTextArea();
        btn_Close = new javax.swing.JButton();
        txt_Ticket = new javax.swing.JTextField();
        lbl_Ticket = new javax.swing.JLabel();
        lbl_Club = new javax.swing.JLabel();
        txt_Club = new javax.swing.JTextField();
        lbl_Bckgrd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Event Approval");
        setBackground(new java.awt.Color(109, 197, 163));
        setLocationByPlatform(true);
        setName("Frame"); // NOI18N
        getContentPane().setLayout(null);

        lbl_Day.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Day.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Day.setText("Day:");
        getContentPane().add(lbl_Day);
        lbl_Day.setBounds(80, 240, 41, 45);

        txt_Venue.setEditable(false);
        txt_Venue.setBackground(new java.awt.Color(255, 255, 255));
        txt_Venue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Venue.setForeground(new java.awt.Color(0, 0, 0));
        txt_Venue.setText("txt_Venue");
        getContentPane().add(txt_Venue);
        txt_Venue.setBounds(130, 310, 243, 45);

        lbl_Name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Name.setText("Name:");
        getContentPane().add(lbl_Name);
        lbl_Name.setBounds(60, 100, 58, 45);

        lbl_Venue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Venue.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Venue.setText("Venue:");
        getContentPane().add(lbl_Venue);
        lbl_Venue.setBounds(60, 310, 64, 45);

        lbl_Budget.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Budget.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Budget.setText("Budget:");
        getContentPane().add(lbl_Budget);
        lbl_Budget.setBounds(50, 380, 70, 45);

        lbl_Date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Date.setText("Date:");
        getContentPane().add(lbl_Date);
        lbl_Date.setBounds(70, 170, 47, 45);

        lbl_Descript.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Descript.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Descript.setText("Description:");
        getContentPane().add(lbl_Descript);
        lbl_Descript.setBounds(10, 450, 107, 45);

        txt_Name.setEditable(false);
        txt_Name.setBackground(new java.awt.Color(255, 255, 255));
        txt_Name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Name.setForeground(new java.awt.Color(0, 0, 0));
        txt_Name.setText("txt_Name");
        getContentPane().add(txt_Name);
        txt_Name.setBounds(130, 100, 243, 45);

        txt_Date.setEditable(false);
        txt_Date.setBackground(new java.awt.Color(255, 255, 255));
        txt_Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Date.setForeground(new java.awt.Color(0, 0, 0));
        txt_Date.setText("txt_Date");
        getContentPane().add(txt_Date);
        txt_Date.setBounds(130, 170, 243, 45);

        txt_Day.setEditable(false);
        txt_Day.setBackground(new java.awt.Color(255, 255, 255));
        txt_Day.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Day.setForeground(new java.awt.Color(0, 0, 0));
        txt_Day.setText("txt_Day");
        getContentPane().add(txt_Day);
        txt_Day.setBounds(130, 240, 243, 45);

        txt_Budget.setEditable(false);
        txt_Budget.setBackground(new java.awt.Color(255, 255, 255));
        txt_Budget.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Budget.setForeground(new java.awt.Color(0, 0, 0));
        txt_Budget.setText("txt_Budget");
        getContentPane().add(txt_Budget);
        txt_Budget.setBounds(130, 380, 243, 45);

        txt_Descript.setEditable(false);
        txt_Descript.setBackground(new java.awt.Color(255, 255, 255));
        txt_Descript.setColumns(20);
        txt_Descript.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Descript.setForeground(new java.awt.Color(0, 0, 0));
        txt_Descript.setRows(5);
        txt_Descript.setText("txt_Descript");
        jScrollPane1.setViewportView(txt_Descript);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 450, 243, 160);

        btn_Approve.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Approve.setText("Approve");
        btn_Approve.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_ApproveMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Approve);
        btn_Approve.setBounds(509, 80, 120, 45);

        btn_Reject.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Reject.setText("Reject");
        btn_Reject.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_RejectMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Reject);
        btn_Reject.setBounds(550, 390, 109, 46);

        lbl_Reject_Reason.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Reject_Reason.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Reject_Reason.setText("Rejection Reason");
        getContentPane().add(lbl_Reject_Reason);
        lbl_Reject_Reason.setBounds(450, 160, 154, 45);

        txt_Reject.setBackground(new java.awt.Color(255, 255, 255));
        txt_Reject.setColumns(20);
        txt_Reject.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Reject.setForeground(new java.awt.Color(0, 0, 0));
        txt_Reject.setRows(5);
        jScrollPane2.setViewportView(txt_Reject);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(390, 220, 270, 160);

        btn_Close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Close.setText("Close");
        btn_Close.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_CloseMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Close);
        btn_Close.setBounds(550, 570, 109, 46);

        txt_Ticket.setBackground(new java.awt.Color(255, 255, 255));
        txt_Ticket.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Ticket.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txt_Ticket);
        txt_Ticket.setBounds(510, 20, 120, 40);

        lbl_Ticket.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ticket.setText("Ticket:");
        getContentPane().add(lbl_Ticket);
        lbl_Ticket.setBounds(410, 20, 70, 40);

        lbl_Club.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_Club.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Club.setText("Club:");
        getContentPane().add(lbl_Club);
        lbl_Club.setBounds(70, 30, 47, 45);

        txt_Club.setEditable(false);
        txt_Club.setBackground(new java.awt.Color(255, 255, 255));
        txt_Club.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Club.setForeground(new java.awt.Color(0, 0, 0));
        txt_Club.setText("txt_Club");
        getContentPane().add(txt_Club);
        txt_Club.setBounds(130, 30, 243, 45);

        lbl_Bckgrd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_Bckgrd);
        lbl_Bckgrd.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method for btn_Approve (it adds data to DB tbl_Up_Event by calling method ins_Pro_Event from class Event)
    private void btn_ApproveMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_ApproveMouseClicked
    {//GEN-HEADEREND:event_btn_ApproveMouseClicked
        String Ticket = txt_Ticket.getText();
        boolean Success;
        int chk = 0;
        
        if (Ticket.isEmpty() || Ticket.equalsIgnoreCase(" "))
        {
            JOptionPane.showMessageDialog(null, "Please, Enter Ticket price.");
            txt_Ticket.requestFocus();
        }
        else
        {
            try
            {
                chk = Integer.parseInt(Ticket);
                
                if (chk > 0)
                {
                    Success = obj_Event.appr_Pro_Event(getTxt_Name(), getTxt_Date(), getTxt_Day(), getTxt_Venue(), getTxt_Budget(), getTxt_Descript(), getTxt_Club(), getTxt_Ticket());
                    
                    if (Success)
                    {
                        JOptionPane.showMessageDialog(this, "Event Approved Successfully");
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Something went wrong");
                        this.dispose();
                    }
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Please, Enter correct Ticket price.");
                txt_Ticket.requestFocus();
            }
        }
    }//GEN-LAST:event_btn_ApproveMouseClicked

//Method for btn_Delete (it deletes data in DB tbl_Up_Event by calling method del_Pro_Event from class Event)
    private void btn_RejectMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_RejectMouseClicked
    {//GEN-HEADEREND:event_btn_RejectMouseClicked
        String remarks = txt_Reject.getText();
        boolean Success;
        
        if (remarks.isEmpty() || remarks.equalsIgnoreCase(" "))
        {
            JOptionPane.showMessageDialog(null, "Please, Enter Remarks.");
            txt_Reject.requestFocus();
        }
        else
        {
            Success = obj_Event.reject_Pro_Event(getTxt_Name(), remarks);
            
            if (Success)
            {
                JOptionPane.showMessageDialog(this, "Event Rejected Successfully");
                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_RejectMouseClicked

    //btn_Close
    private void btn_CloseMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_CloseMouseClicked
    {//GEN-HEADEREND:event_btn_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_CloseMouseClicked

    //GETTER SETTER START
    public String getTxt_Budget()
    {
        return txt_Budget.getText();
    }
    
    public void setTxt_Budget(String Budget)
    {
        this.txt_Budget.setText(Budget);
    }
    
    public String getTxt_Date()
    {
        return txt_Date.getText();
    }
    
    public void setTxt_Date(String Date)
    {
        this.txt_Date.setText(Date);
    }
    
    public String getTxt_Day()
    {
        return txt_Day.getText();
    }
    
    public void setTxt_Day(String Day)
    {
        this.txt_Day.setText(Day);
    }
    
    public String getTxt_Descript()
    {
        return txt_Descript.getText();
    }
    
    public void setTxt_Descript(String Descript)
    {
        this.txt_Descript.setText(Descript);
    }
    
    public String getTxt_Name()
    {
        return txt_Name.getText();
    }
    
    public void setTxt_Name(String Name)
    {
        this.txt_Name.setText(Name);
    }
    
    public String getTxt_Venue()
    {
        return txt_Venue.getText();
    }
    
    public void setTxt_Venue(String Venue)
    {
        this.txt_Venue.setText(Venue);
    }    
    
    public String getTxt_Ticket()
    {
        return txt_Ticket.getText();
    }
    
    public void setTxt_Ticket(String Ticket)
    {
        this.txt_Ticket.setText(Ticket);
    }
    
    public String getTxt_Club()
    {
        return txt_Club.getText();
    }
    
    public void setTxt_Club(String Club)
    {
        this.txt_Club.setText(Club);
    }
    //GETTER SETTER END

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Approve;
    private javax.swing.JButton btn_Close;
    private javax.swing.JButton btn_Reject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Bckgrd;
    private javax.swing.JLabel lbl_Budget;
    private javax.swing.JLabel lbl_Club;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Day;
    private javax.swing.JLabel lbl_Descript;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Reject_Reason;
    private javax.swing.JLabel lbl_Ticket;
    private javax.swing.JLabel lbl_Venue;
    private javax.swing.JTextField txt_Budget;
    private javax.swing.JTextField txt_Club;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_Day;
    private javax.swing.JTextArea txt_Descript;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextArea txt_Reject;
    private javax.swing.JTextField txt_Ticket;
    private javax.swing.JTextField txt_Venue;
    // End of variables declaration//GEN-END:variables
}
