package project;

import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class frm_Detail_Attendee extends javax.swing.JFrame
{
    //Object of class
    frm_Booking obj_frm_Booking;
    Booking obj_Booking;

    public frm_Detail_Attendee()
    {
        try
        {
            initComponents();
            this.setTitle("Registration Form");
            this.setSize(900, 550);
            this.scaleBckgrd();
            this.setLocationRelativeTo(null);
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.setResizable(false);

            //sets rootPanel transparent so image can to shown and sets size of rootpanel same as JFrame
            this.rootPanel.setOpaque(false);
            this.rootPanel.setSize(this.getWidth() - 50, this.getHeight());

            txt_Name.requestFocus();
            Clear();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //Method to set background image on lbl_Bckgrd
    public void scaleBckgrd()
    {
        //Scaling Image for lbl_Bckgrd (Main Background)
        lbl_Bckgrnd.setSize(this.getWidth(), this.getHeight());
        ImageIcon ic_Bckgrnd = new ImageIcon(getClass().getResource("/resources/bckgrnd_Customer.jpeg"));
        Image img_Bckgrnd = ic_Bckgrnd.getImage();
        Image imgScaled_Bckgrnd = img_Bckgrnd.getScaledInstance(lbl_Bckgrnd.getWidth() - 40, lbl_Bckgrnd.getHeight() - 60, Image.SCALE_SMOOTH);
        ImageIcon scaled_Bckgrnd = new ImageIcon(imgScaled_Bckgrnd);
        lbl_Bckgrnd.setIcon(scaled_Bckgrnd);
    }

    //Method to clear fields
    private void Clear()
    {
        txt_Name.setText("");
        txt_Contact.setText("");
        txt_Seats.setText("");
        txt_Bill.setText("");
    }

    //SETTERS START
    public void setTxt_Bill(String Bill)
    {
        this.txt_Bill.setText(Bill);
    }

    public void setTxt_Contact(String Contact)
    {
        this.txt_Contact.setText(Contact);
    }

    public void setTxt_Date(String Date)
    {
        this.txt_Date.setText(Date);
    }

    public void setTxt_Day(String Day)
    {
        this.txt_Day.setText(Day);
    }

    public void setTxt_Ticket(String Ticket)
    {
        this.txt_Ticket.setText(Ticket);
    }

    public void setTxt_Venue(String Venue)
    {
        this.txt_Venue.setText(Venue);
    }

    public void setTxt_Event(String Event)
    {
        this.txt_Event.setText(Event);
    }

    public void setTxt_Name(String Name)
    {
        this.txt_Name.setText(Name);
    }

    public void setTxt_Seats(String txt_Seats)
    {
        this.txt_Seats.setText(txt_Seats);
    }
    //SETTERS END

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rootPanel = new javax.swing.JPanel();
        lbl_Event = new javax.swing.JLabel();
        lbl_Name = new javax.swing.JLabel();
        lbl_Contact = new javax.swing.JLabel();
        lbl_Bill = new javax.swing.JLabel();
        lbl_Seats = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        txt_Event = new javax.swing.JTextField();
        txt_Seats = new javax.swing.JTextField();
        txt_Bill = new javax.swing.JTextField();
        txt_Contact = new javax.swing.JTextField();
        ck_Bahrian = new javax.swing.JCheckBox();
        lbl_Day = new javax.swing.JLabel();
        txt_Day = new javax.swing.JTextField();
        lbl_Date = new javax.swing.JLabel();
        txt_Venue = new javax.swing.JTextField();
        txt_Date = new javax.swing.JTextField();
        lbl_Dis_Bahiran = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_Date2 = new javax.swing.JLabel();
        txt_Dis_Bahrians = new javax.swing.JTextField();
        lbl_Ticket = new javax.swing.JLabel();
        txt_Ticket = new javax.swing.JTextField();
        btn_Clear = new javax.swing.JButton();
        btn_Confrim = new javax.swing.JButton();
        btn_Cal = new javax.swing.JButton();
        btn_Close = new javax.swing.JButton();
        lbl_Bckgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_Event.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Event.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Event.setText("Event Name:");

        lbl_Name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Name.setText("Name:");

        lbl_Contact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Contact.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Contact.setText("Contact #");

        lbl_Bill.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Bill.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Bill.setText("Bill:");

        lbl_Seats.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Seats.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Seats.setText("Seats:");

        txt_Name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Name.setForeground(new java.awt.Color(0, 0, 0));
        txt_Name.setText("jTextField1");

        txt_Event.setEditable(false);
        txt_Event.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Event.setForeground(new java.awt.Color(0, 0, 0));
        txt_Event.setText("txt_Event");

        txt_Seats.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Seats.setForeground(new java.awt.Color(0, 0, 0));
        txt_Seats.setText("jTextField1");

        txt_Bill.setEditable(false);
        txt_Bill.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Bill.setForeground(new java.awt.Color(0, 0, 0));
        txt_Bill.setText("jTextField1");

        txt_Contact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Contact.setForeground(new java.awt.Color(0, 0, 0));
        txt_Contact.setText("jTextField1");

        ck_Bahrian.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ck_Bahrian.setForeground(new java.awt.Color(0, 0, 0));
        ck_Bahrian.setText("Bahrian ?");

        lbl_Day.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Day.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Day.setText("Day:");

        txt_Day.setEditable(false);
        txt_Day.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Day.setForeground(new java.awt.Color(0, 0, 0));
        txt_Day.setText("txt_Day");

        lbl_Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Date.setText("Date:");

        txt_Venue.setEditable(false);
        txt_Venue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Venue.setForeground(new java.awt.Color(0, 0, 0));
        txt_Venue.setText("txt_Venue");

        txt_Date.setEditable(false);
        txt_Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Date.setForeground(new java.awt.Color(0, 0, 0));
        txt_Date.setText("txt_Date");

        lbl_Dis_Bahiran.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Dis_Bahiran.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Dis_Bahiran.setText("Discount for Bahirans:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Enter your details");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_Date2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Date2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Date2.setText("Venue:");

        txt_Dis_Bahrians.setEditable(false);
        txt_Dis_Bahrians.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Dis_Bahrians.setForeground(new java.awt.Color(0, 0, 0));
        txt_Dis_Bahrians.setText("20%");

        lbl_Ticket.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Ticket.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ticket.setText("Ticket Price:");

        txt_Ticket.setEditable(false);
        txt_Ticket.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Ticket.setForeground(new java.awt.Color(0, 0, 0));
        txt_Ticket.setText("2000");

        btn_Clear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Clear.setText("Clear");
        btn_Clear.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_ClearMouseClicked(evt);
            }
        });

        btn_Confrim.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Confrim.setText("Confirm");
        btn_Confrim.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_ConfrimMouseClicked(evt);
            }
        });

        btn_Cal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Cal.setText("Calculate");
        btn_Cal.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_CalMouseClicked(evt);
            }
        });

        btn_Close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Close.setText("Close");
        btn_Close.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_Name)
                                    .addComponent(lbl_Contact)
                                    .addComponent(lbl_Seats)
                                    .addComponent(lbl_Bill))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(ck_Bahrian)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(lbl_Date2))
                            .addComponent(lbl_Dis_Bahiran)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Date, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_Day, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_Event, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Event, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Venue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Dis_Bahrians, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Ticket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_Confrim, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Cal)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Event, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Event, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Date2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Venue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ck_Bahrian))
                        .addGap(18, 18, 18)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Dis_Bahiran, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Dis_Bahrians, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Confrim)
                        .addComponent(btn_Cal)
                        .addComponent(btn_Clear))
                    .addComponent(btn_Close))
                .addContainerGap(485, Short.MAX_VALUE))
        );

        getContentPane().add(rootPanel);
        rootPanel.setBounds(20, 20, 1030, 920);

        lbl_Bckgrnd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Bckgrnd.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_Bckgrnd.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lbl_Bckgrnd.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbl_Bckgrnd);
        lbl_Bckgrnd.setBounds(10, 10, 1050, 940);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method for Btn_Cal (it calculate ticket price by using method cal_Ticket from class Booking)
    private void btn_CalMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_CalMouseClicked
    {//GEN-HEADEREND:event_btn_CalMouseClicked
        obj_Booking = new Booking();

        String seats = txt_Seats.getText();
        String ticket = txt_Ticket.getText();

        boolean bahrian;

        if (ck_Bahrian.isSelected())
        {
            bahrian = true;
        }
        else
        {
            bahrian = false;
        }

        int bill = obj_Booking.cal_Ticket(bahrian, seats, ticket);

        if (bill == 0)
        {
            txt_Seats.requestFocus();
            txt_Seats.setText("");
        }
        else
        {
            txt_Bill.setText(String.valueOf(bill));
        }
    }//GEN-LAST:event_btn_CalMouseClicked

    //Method for btn_Clear
    private void btn_ClearMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_ClearMouseClicked
    {//GEN-HEADEREND:event_btn_ClearMouseClicked
        Clear();
    }//GEN-LAST:event_btn_ClearMouseClicked

    //Method for btn_Close (it takes back to frm_Booking)
    private void btn_CloseMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_CloseMouseClicked
    {//GEN-HEADEREND:event_btn_CloseMouseClicked
        this.dispose();
        obj_frm_Booking = new frm_Booking();
        obj_frm_Booking.setVisible(true);
    }//GEN-LAST:event_btn_CloseMouseClicked

    //Method for btn_Confirm (It adds data to DB tbl_Register by calling method ins_Attendee from class Booking)
    private void btn_ConfrimMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_ConfrimMouseClicked
    {//GEN-HEADEREND:event_btn_ConfrimMouseClicked
        try
        {
            if (txt_Bill.getText().isEmpty() || txt_Bill.getText().equalsIgnoreCase("0"))
            {
                JOptionPane.showMessageDialog(this, "Please, Calculte price.");
            }

            else if (txt_Name.getText().isEmpty() || txt_Contact.getText().isEmpty() || txt_Seats.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please, Enter in all fields");
            }
            else
            {
                boolean Success = obj_Booking.ins_Attendee(txt_Event.getText(), txt_Date.getText(), txt_Day.getText(), txt_Venue.getText(), txt_Name.getText(),
                                                           txt_Contact.getText(), txt_Seats.getText(), txt_Bill.getText());

                if (Success)
                {
                    JOptionPane.showMessageDialog(this, "Registration Successfull.");
                    obj_frm_Booking.setVisible(true);
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Something went wrong.");
                    obj_frm_Booking.setVisible(true);
                    this.dispose();
                }
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_ConfrimMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cal;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Close;
    private javax.swing.JButton btn_Confrim;
    private javax.swing.JCheckBox ck_Bahrian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Bckgrnd;
    private javax.swing.JLabel lbl_Bill;
    private javax.swing.JLabel lbl_Contact;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Date2;
    private javax.swing.JLabel lbl_Day;
    private javax.swing.JLabel lbl_Dis_Bahiran;
    private javax.swing.JLabel lbl_Event;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Seats;
    private javax.swing.JLabel lbl_Ticket;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JTextField txt_Bill;
    private javax.swing.JTextField txt_Contact;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_Day;
    private javax.swing.JTextField txt_Dis_Bahrians;
    private javax.swing.JTextField txt_Event;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Seats;
    private javax.swing.JTextField txt_Ticket;
    private javax.swing.JTextField txt_Venue;
    // End of variables declaration//GEN-END:variables
}
